In [4]:
A= [ [1,2,3],[4,5,6],[7,8,9]]
B= [ [9,8,7],[6,5,4],[3,2,1]]
C= [ [1,2],[3,4],[5,6]]


In [5]:
import numpy as np

def determinante_matriz(A):

    return np.linalg.det(A)

In [6]:
def inversa_matriz(A):
    return np.linalg.inv(A)

In [7]:
print(determinante_matriz(A))

6.66133814775094e-16


In [8]:
D=[[2,2,-5],[3,-3,8],[3,4,3]]

In [9]:
print(inversa_matriz(D))

[[ 0.2611465   0.1656051  -0.00636943]
 [-0.0955414  -0.13375796  0.19745223]
 [-0.13375796  0.01273885  0.07643312]]


In [10]:
print(determinante_matriz(D))

-156.99999999999994
